[project]
name = "dissertation"
license = "MIT"
authors = [
    { name = "Max Weiner", email = "max.weiner@imf.tu-freiberg.de" },
]

[tool.pytask.ini_options]
editor_url_scheme = "pycharm"
paths = ["dissertation"]