[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dissertation"
version = "0"
description = ''
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Max Weiner", email = "max.weiner@imf.tu-freiberg.de" },
]
dependencies = [
    "pytask ~= 0.4",
    "pytask-latex ~= 0.4",
    "pandas",
    "matplotlib",
    "numpy",
    "scipy",
    "schemdraw",
    "jinja2",
    "tomlkit",
    "jupyterlab",
    "sympy",
    "python-language-server",
    "jupyter"
]

[tool.hatch.envs.default]
path = ".venv"

[tool.hatch.envs.default.scripts]
build = "pytask build"
clean = 'pytask clean --mode force'

[tool.pytask.ini_options]
editor_url_scheme = "pycharm"
exclude = [
    ".venv",
    ".idea",
]
