[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dissertation"
version = "0"
description = ''
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Max Weiner", email = "max.weiner@imf.tu-freiberg.de" },
]
dependencies = [
    "pytask ~= 0.4",
    "pytask-latex ~= 0.4",
    "pandas ~= 2.1",
    "matplotlib ~= 3.8",
    "numpy ~= 1.26",
    "scipy ~= 1.11",
    "schemdraw ~= 0.17",
    "tomlkit ~= 0.12",
    "jupyter ~= 1.0",
    "sympy ~= 1.12",
    "python-lsp-server ~= 1.9",
]

[tool.hatch.envs.default]
path = ".venv"

[tool.hatch.envs.default.scripts]
build = "pytask build"
clean = 'pytask clean --mode force'

[tool.hatch.build]
packages = [
    "dissertation"
]

[tool.pytask.ini_options]
editor_url_scheme = "pycharm"
exclude = [
    ".venv",
    ".idea",
]
