# Maths
Vect = '\symbf{#1}'
LagrangeFunction = '\symscr{L}'
LagrangeParameter = '\lambda'
Transposed = '#1^{\symrm{T}}'
Step = '\symrm{\delta}\mspace{-1mu}'
Diff = '\symrm{\Delta}\mspace{-1mu}'
Deriv = '\symrm{d}\mspace{-1mu}'

# Polar Coordinates
Radius = 'r' # Radius coordinate
Angle = '\varphi'

# Cartesian Coordinates
X = 'x'
Y = 'y'

Time = 't'

# Geometry
Curvature = '\kappa'
Volume = 'V'
Area = 'A'
SurfaceDistance = 'a'
SurfaceRadiusAngle = '\alpha'
SurfaceVectorAngle = '\delta'
Shift = 's'
RotationAngle = '\omega'

# Thermodynamics
Temperature = 'T'
CelsiusTemperature = '\vartheta'
Pressure = 'p'
GasConstant = 'R'
BoltzmannConstant = 'k_{\symrm{B}}'
MolarVolume = 'V_{\symrm{m}}'
Flux = 'j'
VacancyConcentration = '\xi'
DiffusionCoefficient = 'D'
InternalStateVariable = 'x'
InternalStateVelocity = '\dot{x}'
ExternalStateVariable = 'X'
RequiredConstraint = 'f'
AddionalConstraint = 'g'
AuxiliaryVariable = '\xi'

# Energy
GibbsEnergy = 'G'
InterfaceEnergy = '\gamma'
Dissipation = '\symscr{D}'
DissipationFunction = '\symscr{Q}'
Potential = '\mu'

# Indizes
Surface = '\symrm{S}'
GrainBoundary = '\symrm{GB}'
Neck = '\symrm{N}'
Upper = '\symrm{u}'
Lower = '\symrm{l}'
Parent = '\symrm{p}'
Child = '\symrm{c}'
Left = '\symrm{L}'
Right = '\symrm{R}'
Matrix = '\symrm{M}'
Contact = '\symrm{C}'
Normal = '\perp'
Tangential = '\|'
Particle = '\symrm{P}'
Standard = '\circ'
Regarding = '^{|#1}'

# Sets
Nodes = '\symbb{N}'
Particles = '\symbb{P}'