# Maths
diff = '\mathrm{d}'
vect = '\boldsymbol{#1}'
LagrangeFunction = '\mathcal{L}'
LagrangeParameter = '\lambda'

# Polar Coordinates
Radius = 'r' # Radius coordinate
Angle = '\varphi'

# Cartesian Coordinates
X = 'x'
Y = 'y'

# Geometry
Curvature = '\kappa'
Volume = 'V'
Area = 'A'
SurfaceDistance = 'a'
Shift = 's'
RotationAngle = '\omega'

# Thermodynamics
Temperature = 'T'
CelsiusTemperature = '\vartheta'
Pressure = 'p'
GasConstant = 'R'
BoltzmannConstant = 'k_\mathrm{B}'
MolarVolume = 'V_\mathrm{m}'
Flux = 'j'
VacancyConcentration = '\xi'
DiffusionCoefficient = 'D'
InternalStateVariable = 'x'
InternalStateVelocity = '\dot{x}'
ExternalStateVariable = 'X'
RequiredConstraint = 'f'
AddionalConstraint = 'g'

# Energy
GibbsEnergy = 'G'
InterfaceEnergy = '\gamma'
Dissipation = '\mathcal{D}'
DissipationFunction = '\mathcal{Q}'
Potential = '\mu'

# Indizes
Surface = '#1_\mathrm{S}'
GrainBoundary = '#1_\mathrm{GB}'
Neck = '#1_\mathrm{N}'
Upper = '#1_\mathrm{u}'
Lower = '#1_\mathrm{l}'
Matrix = '#1_\mathrm{M}'
Normal = '#1_{\perp}'
Tangential = '#1_{\|}'
Particle = '#1_\mathrm{P}'
Standard = '#1^{\circ}'

# Numerics
TimeStep = '\Delta\mspace{-1mu} t'
ShiftStep = '\Delta\mspace{-1mu} s'
InternalStateStep = '\Delta\mspace{-0.5mu} \InternalStateVariable'